FROM python:3.13.0

# Get latest testrunner::master
RUN git clone --branch master https://github.com/couchbase/testrunner.git
WORKDIR /testrunner
RUN git submodule init
RUN git submodule update --init --force --remote
RUN python -m pip install paramiko boto3 httplib2 setuptools google-cloud-compute google.cloud.dns dnspython couchbase==4.4.0

# Configure dummy user/email for cherry-picks to work
RUN git config user.name qe_dispatcher
RUN git config user.email qe@couchbase.com
RUN git config pull.rebase true

WORKDIR /
# Create a mini-scipt to refresh master on each run
RUN echo "cd /testrunner" > dispatcher.sh
RUN echo "git pull -q" >> dispatcher.sh
RUN echo "python -u scripts/testDispatcher_sdk4.py \"\$@\"" >> dispatcher.sh

# Set entrypoint for the docker container
ENTRYPOINT ["sh", "dispatcher.sh"]
